<form action="" method="POST" class="form-signin admin-login">
    <h2 class="form-signin-heading">Admin panel</h2>
    <input type="text" name="login" class="form-control" placeholder="Login">
    <input type="password" name="password" class="form-control" placeholder="Password">
    <?php if ($invalidCredentials) { ?>
        <div class="alert alert-danger">
            Invalid credentials
        </div>
    <?php } ?>
    <button class="btn btn-large btn-primary" type="submit">Sign in</button>
</form>