<form action="" method="POST" class="admin-form">
    <h2 class="form-signin-heading">New page</h2>
    <input name="url" class="form-control" placeholder="Url" value="<?php echo $url; ?>">
    <input name="title" class="form-control" placeholder="Title" value="<?php echo $title; ?>">
    <textarea name="content" class="form-control" placeholder="content"><?php echo $content; ?></textarea>
    <?php if ($errorMessage) { ?>
        <div class="alert alert-danger">
            <?php echo $errorMessage; ?>
        </div>
    <?php } ?>
    <button class="btn btn-large btn-primary" type="submit">Save</button>
</form>