<div class="panel panel-default admin-pages">
    <div class="panel-heading"><?php echo $t('pages_list_title'); ?></div>

    <table class="table">
        <tr class="non-draggable">
            <th width="200"><?php echo $t('common_url'); ?></th>
            <th><?php echo $t('common_title'); ?></th>
            <th width="70"></th>
            <th width="70"></th>
        </tr>
        <?php foreach($data['pages'] as $page) { ?>
            <tr>
                <td>
                    <input type="hidden" class="hidden" value="<?php echo $page->id; ?>" />
                    <?php echo $page->id; ?>
                </td>
                <td><?php echo $page->title; ?></td>
                <td width="100">
                    <a href="/admin/pagesedit/<?php echo $page->id; ?>"><?php echo $t('common_edit'); ?></a>
                </td>                
                <td width="100">
                    <a href="#" 
                       class="entity-delete" 
                       data-confirmation="<?php echo $t('common_are_you_sure'); ?>"
                       data-href="/admin/pagesDelete" 
                       data-id="<?php echo $page->id; ?>"
                       ><?php echo $t('common_delete'); ?></a>
                </td>
            </tr>
        <?php } ?>
        <tr class="non-draggable">
            <td><a href="/admin/pagesnew"><?php echo $t('common_add_new'); ?></a></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>

<div class="alert alert-success" id="success-pages"><?php echo $t('common_saved'); ?></div>
<div class="alert alert-danger" id="error-pages"><?php echo $t('common_failed'); ?></div>