<form action="" method="POST" class="admin-form">
    <h2 class="form-signin-heading"><?php echo $t('pages_create_title'); ?></h2>
    <input id="upload-file-url" type="hidden" value="<?php echo $data['uploadFileUrl']; ?>" />
    <input id="upload-image-url" type="hidden" value="<?php echo $data['uploadImageUrl']; ?>" />
    <input name="url" 
           class="form-control" 
           placeholder="<?php echo $t('common_url'); ?>" 
           value="<?php echo $data['url']; ?>">
    <input name="title" 
           class="form-control" 
           placeholder="<?php echo $t('common_title'); ?>" 
           value="<?php echo $data['title']; ?>">
    <textarea name="content" 
              id="page-content"
              class="form-control" 
              placeholder="<?php echo $t('common_content'); ?>">
                  <?php echo $data['content']; ?>
    </textarea>
    <?php if ($data['errorMessage']) { ?>
        <div class="alert alert-danger">
            <?php echo $data['errorMessage']; ?>
        </div>
    <?php } ?>
    <button class="btn btn-large btn-primary" type="submit"><?php echo $t('common_save'); ?></button>
</form>