<h2><?php echo $t('files_list_title'); ?></h2>

<?php if (empty($data['files'])) { ?>
    <div><?php echo $t('common_empty_list'); ?></div>
<?php } else { ?>
    <div class="serve-images">
        <?php foreach ($data['files'] as $file) { ?>
            <a href="#" data-url="<?php echo $file['url']; ?>" class="file-name">
                <img src="<?php echo $file['url']; ?>"
                     alt=""
                     width="200" />
            </a>
        <?php } ?>
    </div>
<?php } ?>