<form action="" method="POST" class="admin-form">
    <h2 class="form-signin-heading">Create user</h2>
    <input name="login" 
           class="form-control" 
           placeholder="Login"
           value="<?php echo $data['login']; ?>">
    <input name="password" 
           class="form-control" 
           placeholder="Password" 
           type="password" />
    <input name="confirm" 
           class="form-control" 
           placeholder="Confirm password" 
           type="password" />
    <?php if ($data['errorMessage']) { ?>
        <div class="alert alert-danger">
            <?php echo $data['errorMessage']; ?>
        </div>
    <?php } ?>
    <button class="btn btn-large btn-primary" type="submit">Save</button>
</form>