<form action="" method="POST" class="admin-form">
    <h2 class="form-signin-heading"><?php echo $t('users_create_title'); ?></h2>
    <input name="login" 
           class="form-control" 
           placeholder="<?php echo $t('common_login'); ?>"
           value="<?php echo $data['login']; ?>">
    <input name="password" 
           class="form-control" 
           placeholder="<?php echo $t('common_password'); ?>" 
           type="password" />
    <input name="confirm" 
           class="form-control" 
           placeholder="<?php echo $t('common_confirm_password'); ?>" 
           type="password" />
    <?php if ($data['errorMessage']) { ?>
        <div class="alert alert-danger">
            <?php echo $data['errorMessage']; ?>
        </div>
    <?php } ?>
    <button class="btn btn-large btn-primary" type="submit"><?php echo $t('common_save'); ?></button>
</form>