<div class="panel panel-default admin-users">
    <div class="panel-heading"><?php echo $t('users_list_title'); ?></div>

    <table class="table">
        <?php foreach($data['users'] as $user) { ?>
            <tr>
                <td><?php echo $user->login; ?></td>
                <td width="70">
                    <a href="/admin/usersEdit/<?php echo $user->login; ?>"><?php echo $t('common_edit'); ?></a>
                </td>
                <td width="70">
                    <a href="#" 
                       class="entity-delete" 
                       data-confirmation="<?php echo $t('common_are_you_sure'); ?>"
                       data-href="/admin/usersDelete" 
                       data-id="<?php echo $user->login; ?>"
                       ><?php echo $t('common_delete'); ?></a>
                </td>
            </tr>
        <?php } ?>
        <tr>
            <td>
                <a href="/admin/usersNew"><?php echo $t('common_add_new'); ?></a>
            </td>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>