<div class="panel panel-default admin-users">
    <div class="panel-heading">Admin users</div>

    <table class="table">
        <?php foreach($data['users'] as $user) { ?>
            <tr>
                <td><?php echo $user->login; ?></td>
                <td width="70"><a href="/admin/usersEdit/<?php echo $user->login; ?>">edit</a></td>
                <td width="70">
                    <a href="#" 
                       class="entity-delete" 
                       data-href="/admin/usersDelete" 
                       data-id="<?php echo $user->login; ?>"
                       >delete</a>
                </td>
            </tr>
        <?php } ?>
        <tr>
            <td><a href="/admin/usersNew">add new</a></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>