<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->title); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php foreach ($this->css as $path) { ?>
            <link href="<?=$path?>" media="screen" rel="stylesheet" type="text/css" />
        <?php } ?>
        <?php foreach ($this->js as $path) { ?>
            <script type="text/javascript" src="<?=$path?>"></script>
        <?php } ?>

    </head>

    <body>        
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Project name</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach ($menu as $item) { ?>
                            <li><a href="<?php echo $item->url; ?>">
                                <?php echo $item->title; ?>
                            </a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="starter-template">
                <?php echo $this->content; ?>
            </div>
                <hr>
                <footer>
                    <p>&copy; Company 2014</p>
                </footer>
          </div>
    </body>
</html>