<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $layout['title'] ?></title>

        <?php foreach ($layout['css'] as $path) { ?>
            <link href="<?=$path?>" media="screen" rel="stylesheet" type="text/css" />
        <?php } ?>
        <?php foreach ($layout['js'] as $path) { ?>
            <script type="text/javascript" src="<?=$path?>"></script>
        <?php } ?>

    </head>

    <body>
        <div class="navbar navbar-inverse main-menu" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/admin"><?php echo $t('admin_menu_settings'); ?></a></li>
                        <li><a href="/admin/pages"><?php echo $t('admin_menu_pages'); ?></a></li>
                        <li><a href="/admin/users"><?php echo $t('admin_menu_users'); ?></a></li>
                        <li><a href="/admin/logout"><?php echo $t('admin_menu_logout'); ?></a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="user-page-content">
                <?php include $view; ?>
            </div>
          </div>
    </body>
</html>