<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $layout['title'] ?></title>

        <?php foreach ($layout['css'] as $path) { ?>
            <link href="<?=$path?>" media="screen" rel="stylesheet" type="text/css" />
        <?php } ?>
        <?php foreach ($layout['js'] as $path) { ?>
            <script type="text/javascript" src="<?=$path?>"></script>
        <?php } ?>

    </head>

    <body>        
        <div class="navbar navbar-inverse project-name" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <a href="/"><?php echo $layout['name']; ?></a>
                    <img src="/static/images/logo.png" alt="logo" class="logo" />
                </div>
            </div>
        </div>
        <div class="navbar navbar-inverse main-menu" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach ($layout['menu'] as $menu) { ?>
                            <?php showMenuItem($menu); ?>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row row-offcanvas row-offcanvas-right user-page-content">
                <?php if (empty($layout['news'])) { ?>
                    <?php include $view; ?>
                <?php } else { ?>                    
                    <div class="col-xs-12 col-sm-9">
                        <?php include $view; ?>
                    </div>
                    <div class="col-xs-6 col-sm-3 sidebar-offcanvas news-sidebar">
                        <h3><a href="/news"><?php echo $t('news_titile'); ?></a></h3>
                        <?php foreach ($layout['news'] as $item) { ?>
                            <div class="news-item">
                                <a href="<?php echo $item->url; ?>" class="news-title">
                                    <?php echo $item->title; ?>
                                </a>
                                <p class="news-short">
                                    <?php echo $item->short; ?>
                                </p>
                                <span class="news-date">
                                    <?php echo date('Y-m-d H:i', $item->date); ?>
                                </span>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
            <!--
            <hr>
            <footer>
                <p>
                Works on <a href="https://github.com/theravel/google_cloud_storage_cms">Google Cloud CMS</a>
                </p>
            </footer>
            -->
        </div>
    </body>
</html>