<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $layout['title'] ?></title>

        <?php foreach ($layout['css'] as $path) { ?>
            <link href="<?=$path?>" media="screen" rel="stylesheet" type="text/css" />
        <?php } ?>
        <?php foreach ($layout['js'] as $path) { ?>
            <script type="text/javascript" src="<?=$path?>"></script>
        <?php } ?>

    </head>

    <body>        
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/"><?php echo $layout['name'] ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach ($layout['menu'] as $item) { ?>
                            <li><a href="<?php echo $item->url; ?>">
                                <?php echo $item->title; ?>
                            </a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="starter-template">
                <?php include $view; ?>
            </div>
                <hr>
                <footer>
                    <p>&copy; Company 2014</p>
                </footer>
          </div>
    </body>
</html>