<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $layout['title'] ?></title>

        <?php foreach ($layout['css'] as $path) { ?>
            <link href="<?=$path?>" media="screen" rel="stylesheet" type="text/css" />
        <?php } ?>
        <?php foreach ($layout['js'] as $path) { ?>
            <script type="text/javascript" src="<?=$path?>"></script>
        <?php } ?>

    </head>

    <body>        
        <div class="navbar navbar-inverse project-name" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <a href="/"><?php echo nl2br(str_replace(' ', '&nbsp;', $layout['name'])); ?></a>
                </div>
            </div>
        </div>
        <div class="navbar navbar-inverse main-menu" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach ($layout['menu'] as $menu) { ?>
                            <li>
                                <?php if ($menu->link) { ?>
                                    <a href="<?php echo $menu->link; ?>">
                                        <?php echo $menu->text; ?>
                                    </a>
                                <?php } else { ?>
                                    <span>
                                        <?php echo $menu->text; ?>
                                    </span>
                                    <ul class="submenu navbar-inverse">
                                    <?php foreach ($menu->children as $submenu) { ?>
                                        <li>
                                            <a href="<?php echo $submenu->link; ?>">
                                                <?php echo $submenu->text; ?>
                                            </a>
                                        </li>
                                    <?php } ?>
                                    </ul>
                                <?php } ?>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row row-offcanvas row-offcanvas-right user-page-content">
                <?php include $view; ?>
            </div>
          </div>
    </body>
</html>